const supportLanguages = [
  ["auto", "auto"],
  ["zh-Hans", "zh-CN"],
  ["zh-Hant", "zh-TW"],
  ["en", "en"],
  ["yue", "粤语"],
  ["wyw", "古文"],
  ["en", "en"],
  ["ja", "ja"],
  ["ko", "ko"],
  ["fr", "fr"],
  ["de", "de"],
  ["es", "es"],
  ["it", "it"],
  ["ru", "ru"],
  ["pt", "pt"],
  ["nl", "nl"],
  ["pl", "pl"],
  ["ar", "ar"],
  ["af", "af"],
  ["am", "am"],
  ["az", "az"],
  ["be", "be"],
  ["bg", "bg"],
  ["bn", "bn"],
  ["bs", "bs"],
  ["ca", "ca"],
  ["ceb", "ceb"],
  ["co", "co"],
  ["cs", "cs"],
  ["cy", "cy"],
  ["da", "da"],
  ["el", "el"],
  ["eo", "eo"],
  ["et", "et"],
  ["eu", "eu"],
  ["fa", "fa"],
  ["fi", "fi"],
  ["fj", "fj"],
  ["fy", "fy"],
  ["ga", "ga"],
  ["gd", "gd"],
  ["gl", "gl"],
  ["gu", "gu"],
  ["ha", "ha"],
  ["haw", "haw"],
  ["he", "he"],
  ["hi", "hi"],
  ["hmn", "hmn"],
  ["hr", "hr"],
  ["ht", "ht"],
  ["hu", "hu"],
  ["hy", "hy"],
  ["id", "id"],
  ["ig", "ig"],
  ["is", "is"],
  ["jw", "jw"],
  ["ka", "ka"],
  ["kk", "kk"],
  ["km", "km"],
  ["kn", "kn"],
  ["ku", "ku"],
  ["ky", "ky"],
  ["la", "lo"],
  ["lb", "lb"],
  ["lo", "lo"],
  ["lt", "lt"],
  ["lv", "lv"],
  ["mg", "mg"],
  ["mi", "mi"],
  ["mk", "mk"],
  ["ml", "ml"],
  ["mn", "mn"],
  ["mr", "mr"],
  ["ms", "ms"],
  ["mt", "mt"],
  ["my", "my"],
  ["ne", "ne"],
  ["no", "no"],
  ["ny", "ny"],
  ["or", "or"],
  ["pa", "pa"],
  ["ps", "ps"],
  ["ro", "ro"],
  ["rw", "rw"],
  ["si", "si"],
  ["sk", "sk"],
  ["sl", "sl"],
  ["sm", "sm"],
  ["sn", "sn"],
  ["so", "so"],
  ["sq", "sq"],
  ["sr", "sr"],
  ["sr-Cyrl", "sr"],
  ["sr-Latn", "sr"],
  ["st", "st"],
  ["su", "su"],
  ["sv", "sv"],
  ["sw", "sw"],
  ["ta", "ta"],
  ["te", "te"],
  ["tg", "tg"],
  ["th", "th"],
  ["tk", "tk"],
  ["tl", "tl"],
  ["tr", "tr"],
  ["tt", "tt"],
  ["ug", "ug"],
  ["uk", "uk"],
  ["ur", "ur"],
  ["uz", "uz"],
  ["vi", "vi"],
  ["xh", "xh"],
  ["yi", "yi"],
  ["yo", "yo"],
  ["zu", "zu"],
];


const revisionPrompts = {
  simplicity: "Revise the following sentences to make them more clear, concise, and coherent.",
  detailed: ". Please note that you need to list the changes and briefly explain why"
};

const revisionPromptsLocalized = {
  "zh-Hant": {
    prompt: "潤色此句",
    detailed: "。請列出修改項目，並簡述修改原因",
  },
  "zh-Hans": {
    prompt: "润色此句",
    detailed: "。请注意要列出更改以及简要解释一下为什么这么修改",
  },
  "ja": {
    prompt: "この文章を装飾する",
    detailed: "。変更点をリストアップし、なぜそのように変更したかを簡単に説明することに注意してください",
  },
  "ru": {
    prompt: "Переформулируйте следующие предложения, чтобы они стали более ясными, краткими и связными",
    detailed: ". Пожалуйста, обратите внимание на необходимость перечисления изменений и краткого объяснения причин таких изменений",
  },
  "wyw": {
    prompt: "润色此句古文",
    detailed: "。请注意要列出更改以及简要解释一下为什么这么修改",
  },
  "yue": {
    prompt: "潤色呢句粵語",
    detailed: "。記住要列出修改嘅內容同簡單解釋下點解要做呢啲更改",
  }
};

exports.supportLanguages = supportLanguages;
exports.langMap = new Map(supportLanguages.map(([key, value]) => [key, value]));
exports.langMapReverse = new Map(
  supportLanguages.map(([standardLang, lang]) => [lang, standardLang])
);

exports.revisionPrompts = revisionPrompts;
exports.revisionPromptsLocalized = revisionPromptsLocalized;